### ISSUE TITLE
Implement google play login

### ISSUE THREAD

**Issue by akrimelzer** [oddaspa/TDT4240#7]

**Comment by akrimelzer** [comment]
https://github.com/MrStahlfelge/gdx-gamesvcs

**Comment by Gudzy** [comment]
Her står det om turn based mulitplayer med google play service integrasjonen som nå skal være implementert. https://github.com/MrStahlfelge/gdx-gamesvcs/wiki/Google-Play-Games

**Comment by akrimelzer** [comment]
kødder du? fikset du det så fort?

**Comment by Gudzy** [comment]
Har tilgang til klienter, men litt vanskelig å skjønne hvilken man trenger
for å få det vi behøver. Sendes i ring rundt i repoer

tor. 4. apr. 2019 kl. 16:49 skrev akrimelzer <notifications@github.com>:
